packages:
  [
    "@types/@*/*",
    "@types/*",
    packages/*/*,
    packages/*/*/tests,
    packages/*/*/bench,
    demos/*,
    demos/*/tests,
    "workspace/@*/*",
    "workspace/@*/*/tests",
    "workspace/*",
    "workspace/*/tests",
    ".yalc/*",
    ".yalc/@*/*"
  ]
